name: portfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # Use a specific version
  async: ^2.11.0  # Updated to the latest compatible version
  http: ^1.2.2
  url_launcher: ^6.1.5
  get: ^4.6.6
  youtube_player_flutter: ^9.1.1
  vibration: ^1.8.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Downgraded to a compatible version

# Adjusted dependencies based on the latest available versions
dependency_overrides:
  boolean_selector: ^2.1.2
  characters: ^1.3.1
  clock: ^1.1.2
  collection: ^1.19.1
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  lints: ^5.0.0  # Ensure this matches the downgraded flutter_lints
  matcher: ^0.12.17
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  path: ^1.9.1
  stack_trace: ^1.12.0
  string_scanner: ^1.4.0
  test_api: ^0.7.3
  vm_service: ^14.3.1

flutter:
  uses-material-design: true
  assets:
    - images/waitingImage.jpg
    - images/loadingVehicle.gif
    - images/swiggy.png
    - images/zepto.png
    - images/blinkit.png
    - images/bigbasket.png
    - images/logo1.jpg
    - images/logo2.jpg
    - images/cook.jpg
    - images/stewLogo.png
    - images/stew.jpg
  fonts:
    - family: FontMain
      fonts:
        - asset: fonts/Poppins-Medium.ttf
#        - asset: fonts/FiraMono-Bold.ttf
#          weight: 700
#  - family: CustomFont
#    fonts:
#      - asset: fonts/YourCustomFont-Regular.ttf
#      - asset: fonts/YourCustomFont-Italic.ttf
#        style: italic

